# Generated by Django 5.1.3 on 2024-11-12 19:02

import rideshare.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('DriverID', models.CharField(default=rideshare.models.generate_random_id, max_length=8, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('VehicleNumberPlate', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('PassengerID', models.CharField(default=rideshare.models.generate_random_id, max_length=8, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
    ]
