# Generated by Django 5.1.3 on 2024-12-17 16:53

import rideshare.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_rides',
            fields=[
                ('ride_id', models.CharField(default=rideshare.models.generate_random_id, max_length=8, primary_key=True, serialize=False)),
                ('female_only', models.BooleanField(default=False)),
                ('start', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=100)),
                ('vehicle_no', models.CharField(max_length=20)),
                ('total_distance', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('passenger_count', models.IntegerField()),
                ('passenger_details', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(default=rideshare.models.generate_random_id, max_length=8, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('profile_pic', models.CharField(max_length=100)),
                ('chats', models.JSONField(default=list)),
                ('previous_rides', models.JSONField(default=list)),
            ],
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
