# Generated by Django 5.1.3 on 2024-12-17 19:53

import rideshare.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0002_all_rides_customer_delete_driver_delete_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_rides',
            name='shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='all_rides',
            name='vehicle_no',
            field=models.CharField(default=rideshare.models.generate_random_id, max_length=20),
        ),
    ]
