# Generated by Django 5.1.3 on 2024-12-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0004_alter_all_rides_passenger_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_rides',
            name='passenger_details',
            field=models.JSONField(default=None, null=True),
        ),
    ]
