# Generated by Django 5.1.4 on 2024-12-30 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0006_remove_all_rides_passenger_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('distance', models.FloatField()),
                ('cost', models.FloatField()),
                ('female_only', models.BooleanField(default=False)),
                ('shared', models.BooleanField(default=False)),
                ('ride_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='rideshare.customer')),
            ],
        ),
    ]
