# Generated by Django 5.1.4 on 2025-01-30 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0008_group_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='member_count',
        ),
        migrations.AddField(
            model_name='group',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rideshare.customer'),
        ),
        migrations.AddField(
            model_name='group',
            name='female_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.JSONField(default=list),
        ),
    ]
