# Generated by Django 5.1.4 on 2025-01-30 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0009_remove_group_member_count_group_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='member_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideshare.customer'),
        ),
    ]
