# Generated by Django 5.1.4 on 2025-01-30 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0010_group_member_count_alter_group_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideshare.customer'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(choices=[('NOT_COMING', 'Not coming'), ('LATE_5', 'Late by 5 min'), ('LATE_10', 'Late by 10 min'), ('READY', 'Ready to go')], max_length=255),
        ),
    ]
